spring:
   application:
      name: Product
   datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://${POSTGRES_SERVICE}:5432/${POSTGRES_DB}?useSSL=false
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
   jpa:
      hibernate:
         dialect: org.hibernate.dialect.PostgreSQLDialect
         ddl-auto: create
      properties:
         hibernate:
            jdbc:
               lob:
                  non_contextual_creation: true
server:
   port: 8080